{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "petstore-api.fullname" . }}-secrets
  labels:
    {{- include "petstore-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "petstore-api.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: api_key
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: database_url
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "petstore-api.fullname" . }}-secrets
  labels:
    {{- include "petstore-api.labels" . | nindent 4 }}
type: Opaque
data: {}
{{- end }}
